package com.nqd.nqd_lms_be.entity.enums;

public enum FeatureKey {
    AI_TUTOR,
    PREMIUM_COURSES,
    PREMIUM_EXAMS,
    PDF_DOWNLOAD,
    VIDEO_HIGH_QUALITY,
    AI_EXAM_GENERATION,
    ADVANCED_ANALYTICS,
    QUESTION_BANK_LIMIT,
    CLASS_LIMIT,
    EXAM_LIMIT,
    DISCOUNT_ON_PURCHASES,
    ULTRA_UNLIMITED_COURSES,
    ULTRA_COURSE_ENROLLMENT
}
